export const projects = [
  {
    title: "Art Portfolio",
    infotext: "Some text",
    icon1: "var(--clr-accent)",
    icon2: "var(--clr-accent)",
    icon3: "var(--clr-accent)",
    icon4: "var(--clr-primary)",
    icon5: "var(--clr-primary)",
    icon6: "var(--clr-primary)",
    icon7: "var(--clr-primary)",
    link1: "https://www.niklaswallenborg.com/",
    link2: null,
    imgSrc: require("./img/img001.jpg"),
  },
  {
    title: "Color Me Twice",
    infotext:
      "Color Me Twice has been designed to assist you in creating an 2 color palette for your upcoming web development project. By selecting two colors, Color Me Twice will provide you based on your choice of colors, a primary color and its accompanying accent shade, resulting in a visually cohesive two-color composition.",
    icon1: "var(--clr-accent)",
    icon2: "var(--clr-accent)",
    icon3: "var(--clr-accent)",
    icon4: "var(--clr-accent)",
    icon5: "var(--clr-primary)",
    icon6: "var(--clr-primary)",
    icon7: "var(--clr-primary)",
    link1: "https://www.niklaswallenborg.com/KarlMarxFashion.html",
    link2: "https://www.niklaswallenborg.com/KarlMarxFashion.html",
    imgSrc: require("./img/img005.jpg"),
  },

  {
    title: "Karl Marx Fashion",
    infotext: "Some text",
    icon1: "var(--clr-accent)",
    icon2: "var(--clr-accent)",
    icon3: "var(--clr-accent)",
    icon4: "var(--clr-primary)",
    icon5: "var(--clr-primary)",
    icon6: "var(--clr-primary)",
    icon7: "var(--clr-primary)",
    link1: "https://www.niklaswallenborg.com/KarlMarxFashion.html",
    link2: null,
    imgSrc: require("./img/img002.jpg"),
  },
  {
    title: "Solar System Scroll!",
    infotext: "Some text",
    icon1: "var(--clr-accent)",
    icon2: "var(--clr-accent)",
    icon3: "var(--clr-accent)",
    icon4: "var(--clr-accent)",
    icon5: "var(--clr-primary)",
    icon6: "var(--clr-primary)",
    icon7: "var(--clr-primary)",
    link1: "https://www.niklaswallenborg.com/KarlMarxFashion.html",
    link2: null,
    imgSrc: require("./img/img003.jpg"),
  },
  {
    title: "Going Under Under Ground",
    infotext: "Some text",
    icon1: "var(--clr-accent)",
    icon2: "var(--clr-accent)",
    icon3: "var(--clr-accent)",
    icon4: "var(--clr-primary)",
    icon5: "var(--clr-primary)",
    icon6: "var(--clr-primary)",
    icon7: "var(--clr-primary)",
    link1: "https://going-under-underground.netlify.app/#",
    link2: "https://github.com/Wallenborg",
    imgSrc: require("./img/img008.jpg"),
  },
  {
    title: "The Algorithm Whisper",
    infotext: "Some text",
    icon1: "var(--clr-accent)",
    icon2: "var(--clr-accent)",
    icon3: "var(--clr-accent)",
    icon4: "var(--clr-primary)",
    icon5: "var(--clr-primary)",
    icon6: "var(--clr-primary)",
    icon7: "var(--clr-primary)",
    link1: "https://fanciful-ganache-e9f55c.netlify.app/",
    link2: "https://github.com/Wallenborg",
    imgSrc: require("./img/img006.jpg"),
  },
  {
    title: "API Color Mix System",
    infotext: "Some text",
    icon1: "var(--clr-accent)",
    icon2: "var(--clr-accent)",
    icon3: "var(--clr-accent)",
    icon4: "var(--clr-primary)",
    icon5: "var(--clr-primary)",
    icon6: "var(--clr-primary)",
    icon7: "var(--clr-primary)",
    link1: "https://cosmic-crostata-c8da36.netlify.app/",
    link2: "https://github.com/Wallenborg",
    imgSrc: require("./img/img007.jpg"),
  },
  {
    title: "That's is it! So far",
    infotext: (
      <div>
        <p>Name: Niklas Wallenborg</p>
        <p>Age: 45</p>
        <p>Family: Partner and 2 kids</p>
        <p>
          Hobbies: Art, Politics, Digital Culture, Sci-Fi, Gardening and Walking
        </p>
        <br />
        <p>info@niklaswallenborg.com</p>
      </div>
    ),
    icon1: "var(--clr-accent)",
    icon2: "var(--clr-accent)",
    icon3: "var(--clr-accent)",
    icon4: "var(--clr-accent)",
    icon5: "var(--clr-accent)",
    icon6: "var(--clr-accent)",
    icon7: "var(--clr-accent)",
    link1: null,
    link2: null,
    imgSrc: require("./img/img004.jpg"),
  },
];
